spring:
  datasource:
    generate-unique-name: false
    name: tacocloud

  # 以下的配置不要填写，否则会连接不成功
  #  h2:
  #    console:
  #      enable: true

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 189500217263951
            clientSecret:
            scope: email, public_profile

# Own configuration Properties
#taco:
#  orders:
#    page-size: 2


---

spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

# Using CMD
# can specify more than one active profile
  profiles:
    active:
      - prod
      - audit
      - ha

logging:
  level:
    tacos: WARN



