spring:
  datasource:
    generate-unique-name: false
    name: tacocloud

  data:
    mongodb:
      host: mongodb.tacocloud.com
      port: 27017
      username: tacocloud
      password: s3cr3tp455w0rd
      database: tacoclouddb


#    platform: h2

#    #驱动
#    driver-class-name: org.h2.Driver
#
#    #数据库URL 内存模式
#    #url: jdbc:h2:mem:hello
#
#    #数据库URL嵌入模式
#    url: jdbc:h2:file:D:/D/test
#
#    #数据库账号密码
#    username: sa
#    password: sa
#
#
#  h2:
#    console:
#      enable: true
#
#logging:
#  level:
#    root: INFO

