spring:
  datasource:
    generate-unique-name: false
    name: tacocloud

  # 以下的配置不要填写，否则会连接不成功
  #  h2:
  #    console:
  #      enable: true

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 189500217263951
            clientSecret:
            scope: email, public_profile

# Own configuration Properties
taco:
  orders:
    pageSize: 4